version: '3.6' # docker-compose-single-broker.yml 파일을 수정했다. https://github.com/wurstmeister/kafka-docker
services:
  zookeeper:
    image: zookeeper
    restart: always
    container_name: my-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: my-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: my-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    image: hlebalbau/kafka-manager
    container_name: my-kafka-manager
    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "my-zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: master
      KAFKA_MANAGER_PASSWORD: msa

# zookeeper & kafka 클러스터 실행
## options: 백그라운드로 실행하고 싶을 경우 `-d`를 사용한다.
### docker-compose up -d
# broker 삼중화
### dcoker-compose scale kafka=3
# zookeeper & kafka 클러스터 중지
### docker-compose down
